In [86]:
from sklearn.datasets import load_diabetes

In [87]:
import numpy as np


In [88]:
X,y=load_diabetes(return_X_y=True)

In [89]:
#weight=(xTx)-1 @ xT @ y  y^=XB

In [90]:
class Linreg():
    def __init__(self):
        self.beta=None
    def fit(self,x,y):
        x=np.insert(x,0,1,axis=1)
        self.beta=np.linalg.inv(x.T@x)@x.T@y
    def predict(self,x_test):
        x_test=np.insert(x_test,0,1,axis=1)
        return x_test@self.beta
        
        
    

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=90)

In [93]:
lr=Linreg()

In [94]:
lr.fit(x_train,y_train)

In [95]:
pred=lr.predict(x_test)

In [97]:
pred

array([207.4993808 , 139.48976196,  41.97288575, 174.51069584,
       133.5431587 , 203.04230777, 174.13476655,  95.61194988,
       106.47829767, 179.48693352, 203.56857976, 124.65587865,
       173.83145334, 107.61226362, 148.10243543, 177.81597335,
       164.50767035, 161.91086532, 180.90715474, 169.7591436 ,
        73.82746402, 157.31574208, 163.87479796, 164.73335997,
       235.99958013, 125.49762395, 231.85925102, 113.38050223,
       190.98328404, 139.64262545, 183.71121   , 210.45839504,
       118.30310008, 127.97303515, 138.59323819, 138.59256535,
       286.90247469, 155.11927278,  58.47146362, 124.23604367,
       163.30215892, 115.86752377,  94.43916928,  97.15734701,
       186.69161467, 215.10383477, 155.52184474, 148.3876069 ,
       155.45713526,  96.94229272, 132.7287672 , 257.98752795,
       124.29718764, 246.19645989,  50.71651169, 176.00925135,
        99.64047824, 243.04624801, 113.34891008,  85.34092401,
       203.66405161, 132.61826086, 183.78400814, 113.09

In [98]:
from sklearn.linear_model import LinearRegression

In [99]:
lr=LinearRegression()

In [101]:
lr.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [102]:
pred_2=lr.predict(x_test)

In [104]:
pred

array([207.4993808 , 139.48976196,  41.97288575, 174.51069584,
       133.5431587 , 203.04230777, 174.13476655,  95.61194988,
       106.47829767, 179.48693352, 203.56857976, 124.65587865,
       173.83145334, 107.61226362, 148.10243543, 177.81597335,
       164.50767035, 161.91086532, 180.90715474, 169.7591436 ,
        73.82746402, 157.31574208, 163.87479796, 164.73335997,
       235.99958013, 125.49762395, 231.85925102, 113.38050223,
       190.98328404, 139.64262545, 183.71121   , 210.45839504,
       118.30310008, 127.97303515, 138.59323819, 138.59256535,
       286.90247469, 155.11927278,  58.47146362, 124.23604367,
       163.30215892, 115.86752377,  94.43916928,  97.15734701,
       186.69161467, 215.10383477, 155.52184474, 148.3876069 ,
       155.45713526,  96.94229272, 132.7287672 , 257.98752795,
       124.29718764, 246.19645989,  50.71651169, 176.00925135,
        99.64047824, 243.04624801, 113.34891008,  85.34092401,
       203.66405161, 132.61826086, 183.78400814, 113.09

In [105]:
pred_2

array([207.4993808 , 139.48976196,  41.97288575, 174.51069584,
       133.5431587 , 203.04230777, 174.13476655,  95.61194988,
       106.47829767, 179.48693352, 203.56857976, 124.65587865,
       173.83145334, 107.61226362, 148.10243543, 177.81597335,
       164.50767035, 161.91086532, 180.90715474, 169.7591436 ,
        73.82746402, 157.31574208, 163.87479796, 164.73335997,
       235.99958013, 125.49762395, 231.85925102, 113.38050223,
       190.98328404, 139.64262545, 183.71121   , 210.45839504,
       118.30310008, 127.97303515, 138.59323819, 138.59256535,
       286.90247469, 155.11927278,  58.47146362, 124.23604367,
       163.30215892, 115.86752377,  94.43916928,  97.15734701,
       186.69161467, 215.10383477, 155.52184474, 148.3876069 ,
       155.45713526,  96.94229272, 132.7287672 , 257.98752795,
       124.29718764, 246.19645989,  50.71651169, 176.00925135,
        99.64047824, 243.04624801, 113.34891008,  85.34092401,
       203.66405161, 132.61826086, 183.78400814, 113.09